### ISSUE TITLE
Build app error

### ISSUE THREAD

**Issue by alex-kovalchuk** [bazaglia/shopping-cart#1]
After `npm install` I ran `npm run build` then I got error:

```
> tsc -b

src/infra/database/memory.ts:10:7 - error TS2698: Spread types may only be created from object types.

10       ...value,
         ~~~~~~~~

src/api/http/controller.ts:19:54 - error TS2339: Property 'params' does not exist on type 'BaseContext'.

19     const item = await this._itemService.getById(ctx.params.id)
                                                        ~~~~~~

src/api/http/controller.ts:24:34 - error TS2339: Property 'request' does not exist on type 'BaseContext'.

24     const item = Item.create(ctx.request.body)
                                    ~~~~~~~

src/api/http/controller.ts:30:54 - error TS2339: Property 'params' does not exist on type 'BaseContext'.

30     const cart = await this._cartService.getById(ctx.params.id)
                                                        ~~~~~~

src/api/http/controller.ts:35:28 - error TS2339: Property 'params' does not exist on type 'BaseContext'.

35     const { cartId } = ctx.params
                              ~~~~~~

src/api/http/controller.ts:36:38 - error TS2339: Property 'request' does not exist on type 'BaseContext'.

36     const { itemId, quantity } = ctx.request.body
                                        ~~~~~~~

src/api/http/controller.ts:45:36 - error TS2339: Property 'params' does not exist on type 'BaseContext'.

45     const { cartId, itemId } = ctx.params
                                      ~~~~~~

src/api/http/controller.ts:52:28 - error TS2339: Property 'params' does not exist on type 'BaseContext'.

52     const { cartId } = ctx.params
                              ~~~~~~

src/api/http/middlewares/errorHandler.ts:36:9 - error TS2339: Property 'app' does not exist on type 'BaseContext'.

36     ctx.app.emit('error', err, ctx)
           ~~~

src/api/http/middlewares/errorHandler.ts:56:9 - error TS2339: Property 'app' does not exist on type 'BaseContext'.

56     ctx.app.emit('error', err, ctx)
           ~~~


Found 10 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopping-cart-api@0.1.0 build: `tsc -b`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shopping-cart-api@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Node: v13.6.0
NPM: 6.13.7

**Comment by bazaglia** [comment]
Hi @alex-kovalchuk 

Can you please try with `yarn install` instead? It will use the lock file to install the dependencies and the `@types/koa` from this version allows custom properties on the interface `BaseContext` – what apparently is not the case when you install using npm.

After installing you can use `yarn start` and the server will start in port 3000.

**Comment by alex-kovalchuk** [comment]
Hi @bazaglia,

Thank you! `yarn install` fixed the first issue, but I have new error after run `yarn start`:
```
yarn run v1.21.1
$ ts-node -r tsconfig-paths/register src/main.ts
(node:4087) ExperimentalWarning: The ESM module loader is experimental.
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /private/var/www/shopping-cart/src/main.ts imported from /private/var/www/shopping-cart/
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:126:13)
    at Loader.resolve (internal/modules/esm/loader.js:72:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:156:40)
    at Loader.import (internal/modules/esm/loader.js:140:28)
    at internal/modules/run_main.js:48:38
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by alex-kovalchuk** [comment]
Already not critical for me. Thx!
